#!/bin/sh
CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' \
	-- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

batorcat() {
	file="$1"
	shift
	if command -v bat > /dev/null 2>&1; then
		bat --color=always --style=plain --pager=never "$file" "$@"
	else
		cat "$file"
	fi
}

case $(echo ${1##*.} | tr [:upper:] [:lower:]) in
	a|ace|alz|apk|arc|arj|bz|bz2|cab|cpio|deb|gz|iso|jar|lha|lz|lzh|lzma|lzo|\
		rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst|rar|7z)
			7z l "$1" ;;
	md) batorcat "$1";;
	[1-8]) man "$1" | col -b ;;
	o) nm "$1";;
	torrent) transmission-show "$1" ;;
	iso) iso-info --no-header -l "$1" ;;
	odt|ods|odp|sxw) odt2txt "$1" ;;
	doc) catdoc "$1" ;;
	docx) docx2txt < "$1" ;;
	xml|html) w3m -dump "$1";;
	xls|xlsx)
		ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
		;;
	wav|mp3|flac|m4a|wma|ape|ac3|og[agx]|spx|opus|as[fx]|mka)
		exiftool "$1"
		;;
	pdf)
		[ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	epub)
		[ ! -f "$CACHE" ] && epub-thumbnailer "$1" "$CACHE" 1024
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	cbz|cbr|cbt)
		[ ! -f "$CACHE" ] && comicthumb "$1" "$CACHE" 1024
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	avi|mp4|wmv|dat|3gp|ogv|mkv|mpg|mpeg|vob|fl[icv]|m2v|mov|webm|ts|mts|m4v|r[am]|qt|divx)
		[ ! -f "${CACHE}.jpg" ] && \
			ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		exit 1
		;;
	bmp|jpg|jpeg|png|xpm|webp|tiff|gif|jfif|ico)
		chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
		exit 1
		;;
	svg)
		[ ! -f "${CACHE}.jpg" ] && convert "$1" "${CACHE}.jpg"
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	ino) batorcat --language=cpp "$1" ;;
	*) batorcat "$1" || file -ibL "$1" | grep -q text;;
esac
exit 0
