#!/bin/sh
CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
batorcat() {
	[ -z $(file -ibL "$@" | grep binary) ] && bat --wrap=never --color=always --style=plain "$@"
}

case "$(echo ${1##*.} | tr [:upper:] [:lower:])" in
	a|ace|alz|apk|arc|arj|bz|bz2|cab|cpio|deb|gz|iso|jar|lha|lz|lzh|lzma|lzo|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst|rar|7z) atool -l "$1" ;;
	torrent) transmission-show "$1" ;;
	[1-8]|md|docx|html|odt) pandoc "$1" -t plain ;;
	wav|mp3|flac|m4a|wma|ape|ac3|og[agx]|spx|opus|as[fx]|mka) mediainfo "$1" ;;
	xls|xlsx)
		[ ! -f "${CACHE}.jpg" ] && ssconvert -T Gnumeric_pdf:pdf_assistant "$1" "fd://1" | pdftoppm -jpeg -f 1 -singlefile - "$CACHE"
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	pdf)
		[ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	avi|mp4|wmv|dat|3gp|ogv|mkv|mpg|mpeg|vob|fl[icv]|m2v|mov|webm|mts|m4v|r[am]|qt|divx)
		[ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	bmp|jpg*|jpeg|png|xpm|webp|tiff|gif|jfif|ico)
		chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
		;;
	svg)
		[ ! -f "${CACHE}.jpg" ] && convert "$1" "${CACHE}.jpg"
		chafa -f sixel -s "$2x$3" --animate off --polite on "${CACHE}.jpg"
		;;
	*) batorcat "$1" || file -ibL "$1" && [ -z "$(command -v bat)" ] && notify-send -a lf "bat not installed" ;;
esac
