#!/bin/sh

# profile file. Runs on login. Environmental variables are set here.
# If you don't plan on reverting to bash, you can remove the link in ~/.profile to clean up.

# Adds `~/.local/bin` to $PATH
# [ -d "$HOME/.local/bin" ] && export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
# export BROWSER="google-chrome-stable"
export BROWSER="firefox"

# Color output
export LESS='-R --use-color -Dd+r$Du+b'

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"

export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"

export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"

export CUDA_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/nv"

export WINEARCH="win32"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wine"

# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Other program settings:
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"	#uses FreeType to render fonts for wine

# Native wayland
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	export MOZ_ENABLE_WAYLAND="1"		# Firefox support Wayland
	export QT_QPA_PLATFORM="wayland"	# Qt on wayland
fi

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"
# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
