geometry=50%:50%
autofit-larger=50%x50%
save-position-on-quit=yes
screenshot-directory="~/"
slang=chi							# 自动优先加载中文字幕
sub-font-size=40			# 字幕字号大小

demuxer-max-bytes=1000M	
demuxer-max-back-bytes=200M
demuxer-readahead-secs=300

vo=gpu-next
hwdec=vulkan					# AMD/Intel显卡使用vaapi硬解；Nvidia请改为nvdec; vulkan实测最高能效 240Hz显示器不必开插帧
profile=high-quality	# gpu-hq与之等价 包含scale hdr等设置
cscale=ewa_lanczossharp
dscale=mitchell

ytdl-format=bestvideo+bestaudio
ytdl-raw-options=cookies-from-browser=firefox
ytdl-raw-options=yes-playlist=

[extension.gif]
loop-file=inf
